version: '3'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=iotdb

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
